version: 2
jobs:
  build-and-test:
    working_directory: ~/ITKModuleTemplate-build
    docker:
      - image: insighttoolkit/module-ci:latest
    steps:
      - checkout:
          path: ~/ITKModuleTemplateCookieCutter
      - run:
          name: Evaluate template
          command: |
            python -m pip install cookiecutter
            cd ~/
            python -m cookiecutter --no-input ~/ITKModuleTemplateCookieCutter
      - run:
          name: Configure
          command: |
            cmake \
              -DITK_DIR:PATH=/ITK-build \
              -DBUILD_TESTING:BOOL=ON \
              -DBUILDNAME:STRING=External-ITKModuleTemplate-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM} \
                ~/ITKModuleTemplate
      - run:
          name: Build and Test
          no_output_timeout: 1.0h
          environment:
            CTEST_BUILD_FLAGS: "-j5"
          command: |
            ctest -j 2 -VV -D Experimental
  package:
    working_directory: ~/
    machine: true
    steps:
      - checkout:
          path: ~/ITKModuleTemplateCookieCutter
      - run:
          name: Evaluate template
          command: |
            python -m pip install cookiecutter
            cd ~/
            python -m cookiecutter --no-input ~/ITKModuleTemplateCookieCutter
      - run:
          name: Fetch build script
          command: |
            cd ~/ITKModuleTemplate
            curl -L https://rawgit.com/InsightSoftwareConsortium/ITKPythonPackage/master/scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh -O
            chmod u+x dockcross-manylinux-download-cache-and-build-module-wheels.sh
      - run:
          name: Build Python packages
          no_output_timeout: 1.0h
          command: |
            cd ~/ITKModuleTemplate
            ./dockcross-manylinux-download-cache-and-build-module-wheels.sh
      - store_artifacts:
          path: dist
          destination: dist

workflows:
    version: 2
    build-test-package:
      jobs:
        - build-and-test
        - package
